# Generated by Django 4.2.5 on 2023-11-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
